#!/bin/sh

run_latehook() {
	local newroot="/new_root/"

	/usr/bin/systemd-machine-id-setup --root="${newroot}"

	if [[ -n "${hostname}" ]]; then
		msg ":: Setting hostname for main system to '${hostname}'..."
	elif [[ -e /sys/class/dmi/id/product_uuid ]]; then
		msg ":: Setting hostname to first bits of product uuid..."
		hostname="$(cut -d- -f1 < /sys/class/dmi/id/product_uuid)"
	else
		msg ":: Setting hostname to random string..."
		hostname="$(cut -d- -f1 < /proc/sys/kernel/random/boot_id)"
	fi

	echo -n "${hostname}" > "${newroot}/etc/hostname"
	sed -i "/^127.0.0.1/s/$/\t${hostname}/" "${newroot}/etc/hosts"
}
